name: Build wheels
# pipeline inspired by
# https://github.com/pybind/python_example/blob/master/.github/workflows/wheels.yml

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
     - master
  release:
    types:
      - published

jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Clean dist folder
      run: rm -rf dist

    - name: Build SDist
      run: pipx run build --sdist

    - name: Check metadata
      run: pipx run twine check dist/*

    - uses: actions/upload-artifact@v3
      with:
        name: sdist_distribution
        path: dist/*.tar.gz

  build_wheels:
    name: Build Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Setup CGAL dependencies
      run: |
        wget -nv https://github.com/CGAL/cgal/releases/download/v5.4/CGAL-5.4.tar.xz
        tar -xf CGAL-5.4.tar.xz CGAL-5.4/include/
        mv CGAL-5.4/include/CGAL $GITHUB_WORKSPACE/include/

    - name: Setup boost dependencies
      run: |
        wget -nv https://boostorg.jfrog.io/artifactory/main/release/1.79.0/source/boost_1_79_0.tar.bz2 -O boost_1_79_0.tar.bz2
        tar --bzip2 -xf boost_1_79_0.tar.bz2 boost_1_79_0/boost/
        mv boost_1_79_0/boost $GITHUB_WORKSPACE/include/
        ls -l $GITHUB_WORKSPACE/include/

    - name: Install cibuildwheel
      run: pip install cibuildwheel==2.12.0

    - name: Build wheels
      run: cibuildwheel --output-dir wheelhouse
      env:
        CIBW_BUILD: "{cp37,cp38,cp39,cp310,cp311}-manylinux_x86_64"
        CIBW_BEFORE_BUILD_LINUX: yum -y update && yum -y install gmp-devel mpfr-devel boost boost-thread boost-devel

    - uses: actions/upload-artifact@v3
      with:
        name: wheels
        path: wheelhouse/*.whl
