name: Wheels

on: [push]

jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build SDist
      run: pipx run build --sdist

    - name: Check metadata
      run: pipx run twine check dist/*

    - uses: actions/upload-artifact@v2
      with:
        name: sdist_distribution
        path: dist/*.tar.gz


  build_wheels:
    name: Wheels on ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              os: "ubuntu-latest",
              url: "https://github.com/CGAL/cgal/releases/download/v5.4/CGAL-5.4.tar.xz",
              name: "cgal",
              pathInArchive: "CGAL-5.4/include/",
            }

    steps:
    - uses: actions/checkout@v2

    - name: Setup CGAL dependencies
      run: |
        wget https://github.com/CGAL/cgal/releases/download/v5.4/CGAL-5.4.tar.xz
        tar -xvf CGAL-5.4.tar.xz CGAL-5.4/include/ -C ./include/

    - uses: pypa/cibuildwheel@v2.4.0
      env:
        CIBW_ARCHS_MACOS: auto universal2

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        path: wheelhouse/*.whl
